version: '3'
services:
  postgres:
    image: postgres:14.5-bullseye
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
